AllCops:
  Exclude:
    - '.kitchen/**/*'
    - 'metadata.rb'
    - 'Berksfile'
    - 'test/fixtures/cookbooks/**/*'
    - 'spec/fixtures/**/*'
    - 'Thorfile'

LineLength:
  Max: 200

WordArray:
  Enabled: false

FileName:
  Enabled: false

RegexpLiteral:
  Enabled: false
